# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "modern-ugr-report"
version = "1.0.0"
entrypoint = "src/lib.typ"
authors = ["Pablo Luque Salguero <@pluque01>"]
license = "MIT"
description = "Unofficial University Of Granada report template"
repository = "https://github.com/pluque01/modern-ugr-report"
keywords = ["report", "ugr", "University of Granada"]
categories = ["report"]
compiler = "0.12"
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
